version: '3'
services:
  unipi:
    image: kbeflo/unipi:latest
    container_name: unipi
    restart: always
    volumes:
        - /sys:/sys
        - ${PWD}/config.ini:/unipi/config.ini
    devices:
        - /dev/gpiomem

